---
layout: post
title: "RNP version 0.15 released"
categories: release
authors:
  - name: Nickolay Olshevsky
    email: o.nickolay@gmail.com
    social_links:
      - https://github.com/ni4
excerpt: >-
  API, CLI and FFI enhancements
---

RNP v0.15 has been released on 2021-04-04, providing API, CLI and FFI improvements.


== General

* Added CMake options to allow offline builds, i.e. without `Googletest`/`ruby-rnp` downloads.
* Removed major library version from the library name (`librnp-0.{so,dll}` -> `librnp.{so,dll}`).
* Improved handling of cleartext signatures, when empty line between headers and contents contains some whitespace characters.
* Relaxed requirements for the armored messages CRC (allow absence of the CRC, and issue warning instead of complete failure).
* Updated build instructions for MSVC.
* Improved support of 32-bit platforms (year 2038 problem).

== CLI

* Added up-to-date manual pages for `rnp` and `rnpkeys`.
* rnpkeys: added `--remove-key` command.


== FFI

* Added up-to-date manual page for `librnp`.
* Added function `rnp_signature_remove`
* Added function `rnp_uid_remove`
* Added function `rnp_key_remove_signatures` for batch signature removal and filtering.
