---
layout: post
title: "RNP version 0.15.2 released"
categories: release
authors:
  - name: Nickolay Olshevsky
    email: o.nickolay@gmail.com
    social_links:
      - https://github.com/ni4
excerpt: >-
  Compatibility and security improvements
---

The latest release of RNP v0.15.2 on 2021-08-05 provides compatibility and security improvements.

== General

* Be less strict in userid validation: allow to use userids with self-signature, which has key expiration in the past.
* Do not mark signature as invalid if key which produced it is expired now, but was valid during signing.
* Fix incorrect key expiration calculation in some cases.
* Fix incorrect version number in the `version.txt`.

== FFI

* Add function `rnp_key_get_default_key()` to pick the default key/subkey for the specific operation.
* Allow to pass NULL hash parameter to `rnp_key_add_uid()` to pick the default one.
* Use the same approach as in `rnp_op_encrypt_add_recipient()` for encryption subkey selection in `rnp_key_export_autocrypt()`.

== CLI

* `rnp`: Show error message if encryption failed.
* `rnpkeys` : Add `--expiration` option to specify expiration time during key generation.
